
spring:
  datasource:
    password: Asmae@123
    url: jdbc:mysql://localhost:3306/govthink
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true














