
spring:
  datasource:
    password: Asmae@123
    # En utilisant docker compose : pour se connecter à la BD ( mysql = nom du conteneur dans docker-compose )
    url: jdbc:mysql://mysql:3306/govthink
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true















